name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ secrets.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID from secret
      run: echo $ACCESS_ID